[build]
  command = "npm run build"
  publish = "out"

[[redirects]]
  from = "/job-search"
  to = "/job-search/all"
  status = 301
  force = true

[[redirects]]
  from = "/paywall"
  to = "/job-search/all"
  status = 301
  force = true

[[redirects]]
  from = "/jobs/detail"
  to = "/jobs/detail.html"
  status = 200
  force = false

[[redirects]]
  from = "/jobs/:id"
  to = "/jobs/detail.html"
  status = 200
  force = false

[[redirects]]
  from = "/jobs/*"
  to = "/jobs/detail.html"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
